use crate::clock;
use crate::cpu;
use crate::registers::{self, RegByte, RegFlag, RegWord};
use std::convert::From;

// Load = LD, load right value into left, aka LD_B_C == Load C into B

impl From<u8> for OneByteOpCode {
    fn from(code: u8) -> Self {
        match code {
            // 0x
            0x00 => OneByteOpCode::NOP,
            0x02 => OneByteOpCode::LD_BCcontents_A,
            0x03 => OneByteOpCode::INC_BC,
            0x04 => OneByteOpCode::INC_B,
            0x05 => OneByteOpCode::DEC_B,
            0x07 => OneByteOpCode::RLCA,
            0x09 => OneByteOpCode::ADD_HL_BC,
            0x0A => OneByteOpCode::LD_A_BCcontents,
            0x0B => OneByteOpCode::DEC_BC,
            0x0C => OneByteOpCode::INC_C,
            0x0D => OneByteOpCode::DEC_C,
            0x0F => OneByteOpCode::RRCA,
            // 1x
            0x12 => OneByteOpCode::LD_DEcontents_A,
            0x13 => OneByteOpCode::INC_DE,
            0x14 => OneByteOpCode::INC_D,
            0x15 => OneByteOpCode::DEC_D,
            0x17 => OneByteOpCode::RLA,
            0x19 => OneByteOpCode::ADD_HL_DE,
            0x1A => OneByteOpCode::LD_A_DEcontents,
            0x1B => OneByteOpCode::DEC_DE,
            0x1C => OneByteOpCode::INC_E,
            0x1D => OneByteOpCode::DEC_E,
            0x1F => OneByteOpCode::RRA,
            // 2x
            0x22 => OneByteOpCode::LD_HLincrementedcontents_A,
            0x23 => OneByteOpCode::INC_HL,
            0x24 => OneByteOpCode::INC_H,
            0x25 => OneByteOpCode::DEC_H,
            0x27 => OneByteOpCode::DAA,
            0x29 => OneByteOpCode::ADD_HL_HL,
            0x2A => OneByteOpCode::LD_A_HLincrementedcontents,
            0x2B => OneByteOpCode::DEC_HL,
            0x2C => OneByteOpCode::INC_L,
            0x2D => OneByteOpCode::DEC_L,
            0x2F => OneByteOpCode::CPL,
            // 3x
            0x32 => OneByteOpCode::LD_HLdecrementedcontents_A,
            0x33 => OneByteOpCode::INC_SP,
            0x34 => OneByteOpCode::INC_HLcontents,
            0x35 => OneByteOpCode::DEC_HLcontents,
            0x37 => OneByteOpCode::SCF,
            0x39 => OneByteOpCode::ADD_HL_SP,
            0x3A => OneByteOpCode::LD_A_HLdecrementedcontents,
            0x3B => OneByteOpCode::DEC_SP,
            0x3C => OneByteOpCode::INC_A,
            0x3D => OneByteOpCode::DEC_A,
            0x3F => OneByteOpCode::CCF,
            // 4x
            0x40 => OneByteOpCode::LD_B_B,
            0x41 => OneByteOpCode::LD_B_C,
            0x42 => OneByteOpCode::LD_B_D,
            0x43 => OneByteOpCode::LD_B_E,
            0x44 => OneByteOpCode::LD_B_H,
            0x45 => OneByteOpCode::LD_B_L,
            0x46 => OneByteOpCode::LD_B_HLcontents,
            0x47 => OneByteOpCode::LD_B_A,
            0x48 => OneByteOpCode::LD_C_B,
            0x49 => OneByteOpCode::LD_C_C,
            0x4A => OneByteOpCode::LD_C_D,
            0x4B => OneByteOpCode::LD_C_E,
            0x4C => OneByteOpCode::LD_C_H,
            0x4D => OneByteOpCode::LD_C_L,
            0x4E => OneByteOpCode::LD_C_HLcontents,
            0x4F => OneByteOpCode::LD_C_A,
            // 5x
            0x50 => OneByteOpCode::LD_D_B,
            0x51 => OneByteOpCode::LD_D_C,
            0x52 => OneByteOpCode::LD_D_D,
            0x53 => OneByteOpCode::LD_D_E,
            0x54 => OneByteOpCode::LD_D_H,
            0x55 => OneByteOpCode::LD_D_L,
            0x56 => OneByteOpCode::LD_D_HLcontents,
            0x57 => OneByteOpCode::LD_D_A,
            0x58 => OneByteOpCode::LD_E_B,
            0x59 => OneByteOpCode::LD_E_C,
            0x5A => OneByteOpCode::LD_E_D,
            0x5B => OneByteOpCode::LD_E_E,
            0x5C => OneByteOpCode::LD_E_H,
            0x5D => OneByteOpCode::LD_E_L,
            0x5E => OneByteOpCode::LD_E_HLcontents,
            0x5F => OneByteOpCode::LD_E_A,
            // 6x
            0x60 => OneByteOpCode::LD_H_B,
            0x61 => OneByteOpCode::LD_H_C,
            0x62 => OneByteOpCode::LD_H_D,
            0x63 => OneByteOpCode::LD_H_E,
            0x64 => OneByteOpCode::LD_H_H,
            0x65 => OneByteOpCode::LD_H_L,
            0x66 => OneByteOpCode::LD_H_HLcontents,
            0x67 => OneByteOpCode::LD_H_A,
            0x68 => OneByteOpCode::LD_L_B,
            0x69 => OneByteOpCode::LD_L_C,
            0x6A => OneByteOpCode::LD_L_D,
            0x6B => OneByteOpCode::LD_L_E,
            0x6C => OneByteOpCode::LD_L_H,
            0x6D => OneByteOpCode::LD_L_L,
            0x6E => OneByteOpCode::LD_L_HLcontents,
            0x6F => OneByteOpCode::LD_L_A,
            // 7x
            0x70 => OneByteOpCode::LD_HLcontents_B,
            0x71 => OneByteOpCode::LD_HLcontents_C,
            0x72 => OneByteOpCode::LD_HLcontents_D,
            0x73 => OneByteOpCode::LD_HLcontents_E,
            0x74 => OneByteOpCode::LD_HLcontents_H,
            0x75 => OneByteOpCode::LD_HLcontents_L,
            0x76 => OneByteOpCode::HALT,
            0x77 => OneByteOpCode::LD_HLcontents_A,
            0x78 => OneByteOpCode::LD_A_B,
            0x79 => OneByteOpCode::LD_A_C,
            0x7A => OneByteOpCode::LD_A_D,
            0x7B => OneByteOpCode::LD_A_E,
            0x7C => OneByteOpCode::LD_A_H,
            0x7D => OneByteOpCode::LD_A_L,
            0x7E => OneByteOpCode::LD_A_HLcontents,
            0x7F => OneByteOpCode::LD_A_A,
            // 8x
            0x80 => OneByteOpCode::ADD_A_B,
            0x81 => OneByteOpCode::ADD_A_C,
            0x82 => OneByteOpCode::ADD_A_D,
            0x83 => OneByteOpCode::ADD_A_E,
            0x84 => OneByteOpCode::ADD_A_H,
            0x85 => OneByteOpCode::ADD_A_L,
            0x86 => OneByteOpCode::ADD_A_HLcontents,
            0x87 => OneByteOpCode::ADD_A_A,
            0x88 => OneByteOpCode::ADC_A_B,
            0x89 => OneByteOpCode::ADC_A_C,
            0x8A => OneByteOpCode::ADC_A_D,
            0x8B => OneByteOpCode::ADC_A_E,
            0x8C => OneByteOpCode::ADC_A_H,
            0x8D => OneByteOpCode::ADC_A_L,
            0x8E => OneByteOpCode::ADC_A_HLcontents,
            0x8F => OneByteOpCode::ADC_A_A,
            // 9x
            0x90 => OneByteOpCode::SUB_A_B,
            0x91 => OneByteOpCode::SUB_A_C,
            0x92 => OneByteOpCode::SUB_A_D,
            0x93 => OneByteOpCode::SUB_A_E,
            0x94 => OneByteOpCode::SUB_A_H,
            0x95 => OneByteOpCode::SUB_A_L,
            0x96 => OneByteOpCode::SUB_A_HLcontents,
            0x97 => OneByteOpCode::SUB_A_A,
            0x98 => OneByteOpCode::SBC_A_B,
            0x99 => OneByteOpCode::SBC_A_C,
            0x9A => OneByteOpCode::SBC_A_D,
            0x9B => OneByteOpCode::SBC_A_E,
            0x9C => OneByteOpCode::SBC_A_H,
            0x9D => OneByteOpCode::SBC_A_L,
            0x9E => OneByteOpCode::SBC_A_HLcontents,
            0x9F => OneByteOpCode::SBC_A_A,
            // Ax
            0xA0 => OneByteOpCode::AND_B,
            0xA1 => OneByteOpCode::AND_C,
            0xA2 => OneByteOpCode::AND_D,
            0xA3 => OneByteOpCode::AND_E,
            0xA4 => OneByteOpCode::AND_H,
            0xA5 => OneByteOpCode::AND_L,
            0xA6 => OneByteOpCode::AND_HLcontents,
            0xA7 => OneByteOpCode::AND_A,
            0xA8 => OneByteOpCode::XOR_B,
            0xA9 => OneByteOpCode::XOR_C,
            0xAA => OneByteOpCode::XOR_D,
            0xAB => OneByteOpCode::XOR_E,
            0xAC => OneByteOpCode::XOR_H,
            0xAD => OneByteOpCode::XOR_L,
            0xAE => OneByteOpCode::XOR_HLcontents,
            0xAF => OneByteOpCode::XOR_A,
            // Bx
            0xB0 => OneByteOpCode::OR_B,
            0xB1 => OneByteOpCode::OR_C,
            0xB2 => OneByteOpCode::OR_D,
            0xB3 => OneByteOpCode::OR_E,
            0xB4 => OneByteOpCode::OR_H,
            0xB5 => OneByteOpCode::OR_L,
            0xB6 => OneByteOpCode::OR_HLcontents,
            0xB7 => OneByteOpCode::OR_A,
            0xB8 => OneByteOpCode::CP_B,
            0xB9 => OneByteOpCode::CP_C,
            0xBA => OneByteOpCode::CP_D,
            0xBB => OneByteOpCode::CP_E,
            0xBC => OneByteOpCode::CP_H,
            0xBD => OneByteOpCode::CP_L,
            0xBE => OneByteOpCode::CP_HLcontents,
            0xBF => OneByteOpCode::CP_A,
            // Cx
            0xC0 => OneByteOpCode::RET_NZ,
            0xC1 => OneByteOpCode::POP_BC,
            0xC5 => OneByteOpCode::PUSH_BC,
            0xC7 => OneByteOpCode::RST_00H,
            0xC8 => OneByteOpCode::RET_Z,
            0xC9 => OneByteOpCode::RET,
            0xCF => OneByteOpCode::RST_08H,
            // Dx
            0xD1 => OneByteOpCode::RET_NC,
            0xD2 => OneByteOpCode::POP_DE,
            0xD5 => OneByteOpCode::PUSH_DE,
            0xD7 => OneByteOpCode::RST_10H,
            0xD8 => OneByteOpCode::RET_C,
            0xD9 => OneByteOpCode::RETI,
            0xDF => OneByteOpCode::RST_18H,
            // Ex
            0xE1 => OneByteOpCode::POP_HL,
            0xE2 => OneByteOpCode::LD_Ccontents_A,
            0xE5 => OneByteOpCode::PUSH_HL,
            0xE7 => OneByteOpCode::RST_20H,
            0xE9 => OneByteOpCode::JP_HLcontents,
            0xEF => OneByteOpCode::RST_28H,
            // Fx
            0xF1 => OneByteOpCode::POP_AF,
            0xF2 => OneByteOpCode::LD_A_Ccontents,
            0xF3 => OneByteOpCode::DI,
            0xF5 => OneByteOpCode::PUSH_AF,
            0xF7 => OneByteOpCode::RST_30H,
            0xF9 => OneByteOpCode::LD_SP_HL,
            0xFB => OneByteOpCode::EI,
            0xFF => OneByteOpCode::RST_38H,
            _ => panic!("ERROR::Tried to use an illegal OneByteOpCode. Yoinked by Leopard Claw!"),
        }
    }
}

pub enum OneByteOpCode {
    // TODO: check if dec/incremented commands e..g LD (HL+), if they inc or def before or after command

    // 0x
    NOP = 0x00,
    LD_BCcontents_A = 0x02,
    INC_BC = 0x03,
    INC_B = 0x04,
    DEC_B = 0x05,
    RLCA = 0x07,
    ADD_HL_BC = 0x09,
    LD_A_BCcontents = 0x0A,
    DEC_BC = 0x0B,
    INC_C = 0x0C,
    DEC_C = 0x0D,
    RRCA = 0x0F,

    // 1x
    LD_DEcontents_A = 0x12,
    INC_DE = 0x13,
    INC_D = 0x14,
    DEC_D = 0x15,
    RLA = 0x17,
    ADD_HL_DE = 0x19,
    LD_A_DEcontents = 0x1A,
    DEC_DE = 0x1B,
    INC_E = 0x1C,
    DEC_E = 0x1D,
    RRA = 0x1F,

    // 2x
    LD_HLincrementedcontents_A = 0x22,
    INC_HL = 0x23,
    INC_H = 0x24,
    DEC_H = 0x25,
    DAA = 0x27,
    ADD_HL_HL = 0x29,
    LD_A_HLincrementedcontents = 0x2A,
    DEC_HL = 0x2B,
    INC_L = 0x2C,
    DEC_L = 0x2D,
    CPL = 0x2F,

    // 3x
    LD_HLdecrementedcontents_A = 0x32,
    INC_SP = 0x33,
    INC_HLcontents = 0x34,
    DEC_HLcontents = 0x35,
    SCF = 0x37,
    ADD_HL_SP = 0x39,
    LD_A_HLdecrementedcontents = 0x3A,
    DEC_SP = 0x3B,
    INC_A = 0x3C,
    DEC_A = 0x3D,
    CCF = 0x3F,

    // 4x
    LD_B_B = 0x40,
    LD_B_C = 0x41,
    LD_B_D = 0x42,
    LD_B_E = 0x43,
    LD_B_H = 0x44,
    LD_B_L = 0x45,
    LD_B_HLcontents = 0x46,
    LD_B_A = 0x47,
    LD_C_B = 0x48,
    LD_C_C = 0x49,
    LD_C_D = 0x4A,
    LD_C_E = 0x4B,
    LD_C_H = 0x4C,
    LD_C_L = 0x4D,
    LD_C_HLcontents = 0x4E,
    LD_C_A = 0x4F,

    // 5x
    LD_D_B = 0x50,
    LD_D_C = 0x51,
    LD_D_D = 0x52,
    LD_D_E = 0x53,
    LD_D_H = 0x54,
    LD_D_L = 0x55,
    LD_D_HLcontents = 0x56,
    LD_D_A = 0x57,
    LD_E_B = 0x58,
    LD_E_C = 0x59,
    LD_E_D = 0x5A,
    LD_E_E = 0x5B,
    LD_E_H = 0x5C,
    LD_E_L = 0x5D,
    LD_E_HLcontents = 0x5E,
    LD_E_A = 0x5F,

    // 6x
    LD_H_B = 0x60,
    LD_H_C = 0x61,
    LD_H_D = 0x62,
    LD_H_E = 0x63,
    LD_H_H = 0x64,
    LD_H_L = 0x65,
    LD_H_HLcontents = 0x66,
    LD_H_A = 0x67,
    LD_L_B = 0x68,
    LD_L_C = 0x69,
    LD_L_D = 0x6A,
    LD_L_E = 0x6B,
    LD_L_H = 0x6C,
    LD_L_L = 0x6D,
    LD_L_HLcontents = 0x6E,
    LD_L_A = 0x6F,

    // 7x
    LD_HLcontents_B = 0x70,
    LD_HLcontents_C = 0x71,
    LD_HLcontents_D = 0x72,
    LD_HLcontents_E = 0x73,
    LD_HLcontents_H = 0x74,
    LD_HLcontents_L = 0x75,
    HALT = 0x76,
    LD_HLcontents_A = 0x77,
    LD_A_B = 0x78,
    LD_A_C = 0x79,
    LD_A_D = 0x7A,
    LD_A_E = 0x7B,
    LD_A_H = 0x7C,
    LD_A_L = 0x7D,
    LD_A_HLcontents = 0x7E,
    LD_A_A = 0x7F,

    // 8x
    ADD_A_B = 0x80,
    ADD_A_C = 0x81,
    ADD_A_D = 0x82,
    ADD_A_E = 0x83,
    ADD_A_H = 0x84,
    ADD_A_L = 0x85,
    ADD_A_HLcontents = 0x86,
    ADD_A_A = 0x87,
    ADC_A_B = 0x88,
    ADC_A_C = 0x89,
    ADC_A_D = 0x8A,
    ADC_A_E = 0x8B,
    ADC_A_H = 0x8C,
    ADC_A_L = 0x8D,
    ADC_A_HLcontents = 0x8E,
    ADC_A_A = 0x8F,

    // 9x
    SUB_A_B = 0x90,
    SUB_A_C = 0x91,
    SUB_A_D = 0x92,
    SUB_A_E = 0x93,
    SUB_A_H = 0x94,
    SUB_A_L = 0x95,
    SUB_A_HLcontents = 0x96,
    SUB_A_A = 0x97,
    SBC_A_B = 0x98,
    SBC_A_C = 0x99,
    SBC_A_D = 0x9A,
    SBC_A_E = 0x9B,
    SBC_A_H = 0x9C,
    SBC_A_L = 0x9D,
    SBC_A_HLcontents = 0x9E,
    SBC_A_A = 0x9F,

    // Ax
    AND_B = 0xA0,
    AND_C = 0xA1,
    AND_D = 0xA2,
    AND_E = 0xA3,
    AND_H = 0xA4,
    AND_L = 0xA5,
    AND_HLcontents = 0xA6,
    AND_A = 0xA7,
    XOR_B = 0xA8,
    XOR_C = 0xA9,
    XOR_D = 0xAA,
    XOR_E = 0xAB,
    XOR_H = 0xAC,
    XOR_L = 0xAD,
    XOR_HLcontents = 0xAE,
    XOR_A = 0xAF,

    // Bx
    OR_B = 0xB0,
    OR_C = 0xB1,
    OR_D = 0xB2,
    OR_E = 0xB3,
    OR_H = 0xB4,
    OR_L = 0xB5,
    OR_HLcontents = 0xB6,
    OR_A = 0xB7,
    CP_B = 0xB8,
    CP_C = 0xB9,
    CP_D = 0xBA,
    CP_E = 0xBB,
    CP_H = 0xBC,
    CP_L = 0xBD,
    CP_HLcontents = 0xBE,
    CP_A = 0xBF,

    // Cx
    RET_NZ = 0xC0,
    POP_BC = 0xC1,
    PUSH_BC = 0xC5,
    RST_00H = 0xC7,
    RET_Z = 0xC8,
    RET = 0xC9,
    RST_08H = 0xCF,

    // Dx
    RET_NC = 0xD1,
    POP_DE = 0xD2,
    PUSH_DE = 0xD5,
    RST_10H = 0xD7,
    RET_C = 0xD8,
    RETI = 0xD9,
    RST_18H = 0xDF,

    // Ex
    POP_HL = 0xE1,
    LD_Ccontents_A = 0xE2,

    PUSH_HL = 0xE5,
    RST_20H = 0xE7,
    JP_HLcontents = 0xE9,

    RST_28H = 0xEF,

    // Fx
    POP_AF = 0xF1,
    LD_A_Ccontents = 0xF2,
    DI = 0xF3,
    PUSH_AF = 0xF5,
    RST_30H = 0xF7,
    LD_SP_HL = 0xF9,
    EI = 0xFB,
    RST_38H = 0xFF,
}

impl From<u8> for TwoByteOpCode {
    fn from(code: u8) -> Self {
        match code {
            // 0x
            0x06 => TwoByteOpCode::LD_B_N8,
            0x0E => TwoByteOpCode::LD_C_N8,
            // 1x
            0x10 => TwoByteOpCode::STOP,
            0x16 => TwoByteOpCode::LD_D_N8,
            0x18 => TwoByteOpCode::JR_R8,
            0x1E => TwoByteOpCode::LD_E_N8,
            // 2x
            0x20 => TwoByteOpCode::JR_NZ_R8,
            0x26 => TwoByteOpCode::LD_H_N8,
            0x28 => TwoByteOpCode::JR_Z_R8,
            0x2E => TwoByteOpCode::LD_L_N8,
            // 3x
            0x30 => TwoByteOpCode::JR_NC_R8,
            0x36 => TwoByteOpCode::LD_HLcontents_N8,
            0x38 => TwoByteOpCode::JR_C_R8,
            0x3E => TwoByteOpCode::LD_A_N8,
            // Cx
            0xC6 => TwoByteOpCode::ADD_A_N8,
            0xCE => TwoByteOpCode::ADC_A_N8,
            // Dx
            0xD6 => TwoByteOpCode::SUB_N8,
            0xDE => TwoByteOpCode::SBC_A_N8,
            // Ex
            0xE0 => TwoByteOpCode::LDH_A8contents_A,
            0xE6 => TwoByteOpCode::AND_N8,
            0xE8 => TwoByteOpCode::ADD_SP_R8,
            0xEE => TwoByteOpCode::XOR_N8,
            // Fx
            0xF0 => TwoByteOpCode::LDH_A_A8contents,
            0xF6 => TwoByteOpCode::OR_N8,
            0xF8 => TwoByteOpCode::LD_HL_SPplusR8,
            0xFE => TwoByteOpCode::CP_N8,
            _ => {
                panic!("ERROR::Tried to use an illegal TwoByteOpCode. Yoinked by Polar Bear Claw!")
            }
        }
    }
}

pub enum TwoByteOpCode {
    // 0x
    LD_B_N8 = 0x06,
    LD_C_N8 = 0x0E,

    // 1x
    STOP = 0x10,
    LD_D_N8 = 0x16,
    JR_R8 = 0x18,
    LD_E_N8 = 0x1E,

    // 2x
    JR_NZ_R8 = 0x20,
    LD_H_N8 = 0x26,
    JR_Z_R8 = 0x28,
    LD_L_N8 = 0x2E,

    // 3x
    JR_NC_R8 = 0x30,
    LD_HLcontents_N8 = 0x36,
    JR_C_R8 = 0x38,
    LD_A_N8 = 0x3E,

    // Cx
    ADD_A_N8 = 0xC6,
    ADC_A_N8 = 0xCE,

    // Dx
    SUB_N8 = 0xD6,
    SBC_A_N8 = 0xDE,

    // Ex
    LDH_A8contents_A = 0xE0, // TODO: ???
    AND_N8 = 0xE6,
    ADD_SP_R8 = 0xE8,
    XOR_N8 = 0xEE,

    // Fx
    LDH_A_A8contents = 0xF0, // TODO: ???
    OR_N8 = 0xF6,
    LD_HL_SPplusR8 = 0xF8,
    CP_N8 = 0xFE,
}

impl From<u8> for ThreeByteOpCode {
    fn from(code: u8) -> Self {
        match code {
            // 0x
            0x01 => ThreeByteOpCode::LD_BC_D16,
            0x08 => ThreeByteOpCode::LD_A16contents_SP,
            // 1x
            0x11 => ThreeByteOpCode::LD_DE_D16,
            // 2x
            0x21 => ThreeByteOpCode::LD_HL_D16,
            // 3x
            0x31 => ThreeByteOpCode::LD_SP_D16,
            // Cx
            0xC2 => ThreeByteOpCode::JP_NZ_A16,
            0xC3 => ThreeByteOpCode::JP_A16,
            0xC4 => ThreeByteOpCode::CALL_NZ_A16,
            0xCA => ThreeByteOpCode::JP_Z_A16,
            0xCC => ThreeByteOpCode::CALL_Z_A16,
            0xCD => ThreeByteOpCode::CALL_A16,
            // Dx
            0xD2 => ThreeByteOpCode::JP_NC_A16,
            0xD4 => ThreeByteOpCode::CALL_NC_A16,
            0xDA => ThreeByteOpCode::JP_C_16,
            0xDC => ThreeByteOpCode::CALL_C_A16,
            // Ex
            0xEA => ThreeByteOpCode::LD_A16contents_A,
            // Fx
            0xFA => ThreeByteOpCode::LD_A_A16contents,
            _ => panic!(
                "ERROR::Tried to use an illegal ThreeByteOpCode. Yoinked by Mountain Lion Claw!"
            ),
        }
    }
}
pub enum ThreeByteOpCode {
    // 0x
    LD_BC_D16 = 0x01,
    LD_A16contents_SP = 0x08, // TODO: ???

    // 1x
    LD_DE_D16 = 0x11,

    // 2x
    LD_HL_D16 = 0x21,

    // 3x
    LD_SP_D16 = 0x31,

    // Cx
    JP_NZ_A16 = 0xC2,
    JP_A16 = 0xC3,
    CALL_NZ_A16 = 0xC4,
    JP_Z_A16 = 0xCA,
    CALL_Z_A16 = 0xCC,
    CALL_A16 = 0xCD,

    // Dx
    JP_NC_A16 = 0xD2,
    CALL_NC_A16 = 0xD4,
    JP_C_16 = 0xDA,
    CALL_C_A16 = 0xDC,

    // Ex
    LD_A16contents_A = 0xEA, // TODO: ???

    // Fx
    LD_A_A16contents = 0xFA, // TODO: ???
}

impl From<u8> for PrefixOpCode {
    fn from(code: u8) -> Self {
        match code {
            // 0x
            0x00 => PrefixOpCode::RLC_B,
            0x01 => PrefixOpCode::RLC_C,
            0x02 => PrefixOpCode::RLC_D,
            0x03 => PrefixOpCode::RLC_E,
            0x04 => PrefixOpCode::RLC_H,
            0x05 => PrefixOpCode::RLC_L,
            0x06 => PrefixOpCode::RLC_HLcontents,
            0x07 => PrefixOpCode::RLC_A,
            0x08 => PrefixOpCode::RRC_B,
            0x09 => PrefixOpCode::RRC_C,
            0x0A => PrefixOpCode::RRC_D,
            0x0B => PrefixOpCode::RRC_E,
            0x0C => PrefixOpCode::RRC_H,
            0x0D => PrefixOpCode::RRC_L,
            0x0E => PrefixOpCode::RRC_HLcontents,
            0x0F => PrefixOpCode::RRC_A,
            // 1x
            0x10 => PrefixOpCode::RL_B,
            0x11 => PrefixOpCode::RL_C,
            0x12 => PrefixOpCode::RL_D,
            0x13 => PrefixOpCode::RL_E,
            0x14 => PrefixOpCode::RL_H,
            0x15 => PrefixOpCode::RL_L,
            0x16 => PrefixOpCode::RL_HLcontents,
            0x17 => PrefixOpCode::RL_A,
            0x18 => PrefixOpCode::RR_B,
            0x19 => PrefixOpCode::RR_C,
            0x1A => PrefixOpCode::RR_D,
            0x1B => PrefixOpCode::RR_E,
            0x1C => PrefixOpCode::RR_H,
            0x1D => PrefixOpCode::RR_L,
            0x1E => PrefixOpCode::RR_HLcontents,
            0x1F => PrefixOpCode::RR_A,
            // 2x
            0x20 => PrefixOpCode::SLA_B,
            0x21 => PrefixOpCode::SLA_C,
            0x22 => PrefixOpCode::SLA_D,
            0x23 => PrefixOpCode::SLA_E,
            0x24 => PrefixOpCode::SLA_H,
            0x25 => PrefixOpCode::SLA_L,
            0x26 => PrefixOpCode::SLA_HLcontents,
            0x27 => PrefixOpCode::SLA_A,
            0x28 => PrefixOpCode::SRA_B,
            0x29 => PrefixOpCode::SRA_C,
            0x2A => PrefixOpCode::SRA_D,
            0x2B => PrefixOpCode::SRA_E,
            0x2C => PrefixOpCode::SRA_H,
            0x2D => PrefixOpCode::SRA_L,
            0x2E => PrefixOpCode::SRA_HLcontents,
            0x2F => PrefixOpCode::SRA_A,
            // 3x
            0x30 => PrefixOpCode::SWAP_B,
            0x31 => PrefixOpCode::SWAP_C,
            0x32 => PrefixOpCode::SWAP_D,
            0x33 => PrefixOpCode::SWAP_E,
            0x34 => PrefixOpCode::SWAP_H,
            0x35 => PrefixOpCode::SWAP_L,
            0x36 => PrefixOpCode::SWAP_HLcontents,
            0x37 => PrefixOpCode::SWAP_A,
            0x38 => PrefixOpCode::SRL_B,
            0x39 => PrefixOpCode::SRL_C,
            0x3A => PrefixOpCode::SRL_D,
            0x3B => PrefixOpCode::SRL_E,
            0x3C => PrefixOpCode::SRL_H,
            0x3D => PrefixOpCode::SRL_L,
            0x3E => PrefixOpCode::SRL_HLcontents,
            0x3F => PrefixOpCode::SRL_A,
            // 4x
            0x40 => PrefixOpCode::BIT_0_B,
            0x41 => PrefixOpCode::BIT_0_C,
            0x42 => PrefixOpCode::BIT_0_D,
            0x43 => PrefixOpCode::BIT_0_E,
            0x44 => PrefixOpCode::BIT_0_H,
            0x45 => PrefixOpCode::BIT_0_L,
            0x46 => PrefixOpCode::BIT_0_HLcontents,
            0x47 => PrefixOpCode::BIT_0_A,
            0x48 => PrefixOpCode::BIT_1_B,
            0x49 => PrefixOpCode::BIT_1_C,
            0x4A => PrefixOpCode::BIT_1_D,
            0x4B => PrefixOpCode::BIT_1_E,
            0x4C => PrefixOpCode::BIT_1_H,
            0x4D => PrefixOpCode::BIT_1_L,
            0x4E => PrefixOpCode::BIT_1_HLcontents,
            0x4F => PrefixOpCode::BIT_1_A,
            // 5x
            0x50 => PrefixOpCode::BIT_2_B,
            0x51 => PrefixOpCode::BIT_2_C,
            0x52 => PrefixOpCode::BIT_2_D,
            0x53 => PrefixOpCode::BIT_2_E,
            0x54 => PrefixOpCode::BIT_2_H,
            0x55 => PrefixOpCode::BIT_2_L,
            0x56 => PrefixOpCode::BIT_2_HLcontents,
            0x57 => PrefixOpCode::BIT_2_A,
            0x58 => PrefixOpCode::BIT_3_B,
            0x59 => PrefixOpCode::BIT_3_C,
            0x5A => PrefixOpCode::BIT_3_D,
            0x5B => PrefixOpCode::BIT_3_E,
            0x5C => PrefixOpCode::BIT_3_H,
            0x5D => PrefixOpCode::BIT_3_L,
            0x5E => PrefixOpCode::BIT_3_HLcontents,
            0x5F => PrefixOpCode::BIT_3_A,
            // 6x
            0x60 => PrefixOpCode::BIT_4_B,
            0x61 => PrefixOpCode::BIT_4_C,
            0x62 => PrefixOpCode::BIT_4_D,
            0x63 => PrefixOpCode::BIT_4_E,
            0x64 => PrefixOpCode::BIT_4_H,
            0x65 => PrefixOpCode::BIT_4_L,
            0x66 => PrefixOpCode::BIT_4_HLcontents,
            0x67 => PrefixOpCode::BIT_4_A,
            0x68 => PrefixOpCode::BIT_5_B,
            0x69 => PrefixOpCode::BIT_5_C,
            0x6A => PrefixOpCode::BIT_5_D,
            0x6B => PrefixOpCode::BIT_5_E,
            0x6C => PrefixOpCode::BIT_5_H,
            0x6D => PrefixOpCode::BIT_5_L,
            0x6E => PrefixOpCode::BIT_5_HLcontents,
            0x6F => PrefixOpCode::BIT_5_A,
            // 7x
            0x70 => PrefixOpCode::BIT_6_B,
            0x71 => PrefixOpCode::BIT_6_C,
            0x72 => PrefixOpCode::BIT_6_D,
            0x73 => PrefixOpCode::BIT_6_E,
            0x74 => PrefixOpCode::BIT_6_H,
            0x75 => PrefixOpCode::BIT_6_L,
            0x76 => PrefixOpCode::BIT_6_HLcontents,
            0x77 => PrefixOpCode::BIT_6_A,
            0x78 => PrefixOpCode::BIT_7_B,
            0x79 => PrefixOpCode::BIT_7_C,
            0x7A => PrefixOpCode::BIT_7_D,
            0x7B => PrefixOpCode::BIT_7_E,
            0x7C => PrefixOpCode::BIT_7_H,
            0x7D => PrefixOpCode::BIT_7_L,
            0x7E => PrefixOpCode::BIT_7_HLcontents,
            0x7F => PrefixOpCode::BIT_7_A,
            // 8x
            0x80 => PrefixOpCode::RES_0_B,
            0x81 => PrefixOpCode::RES_0_C,
            0x82 => PrefixOpCode::RES_0_D,
            0x83 => PrefixOpCode::RES_0_E,
            0x84 => PrefixOpCode::RES_0_H,
            0x85 => PrefixOpCode::RES_0_L,
            0x86 => PrefixOpCode::RES_0_HLcontents,
            0x87 => PrefixOpCode::RES_0_A,
            0x88 => PrefixOpCode::RES_1_B,
            0x89 => PrefixOpCode::RES_1_C,
            0x8A => PrefixOpCode::RES_1_D,
            0x8B => PrefixOpCode::RES_1_E,
            0x8C => PrefixOpCode::RES_1_H,
            0x8D => PrefixOpCode::RES_1_L,
            0x8E => PrefixOpCode::RES_1_HLcontents,
            0x8F => PrefixOpCode::RES_1_A,
            // 9x
            0x90 => PrefixOpCode::RES_2_B,
            0x91 => PrefixOpCode::RES_2_C,
            0x92 => PrefixOpCode::RES_2_D,
            0x93 => PrefixOpCode::RES_2_E,
            0x94 => PrefixOpCode::RES_2_H,
            0x95 => PrefixOpCode::RES_2_L,
            0x96 => PrefixOpCode::RES_2_HLcontents,
            0x97 => PrefixOpCode::RES_2_A,
            0x98 => PrefixOpCode::RES_3_B,
            0x99 => PrefixOpCode::RES_3_C,
            0x9A => PrefixOpCode::RES_3_D,
            0x9B => PrefixOpCode::RES_3_E,
            0x9C => PrefixOpCode::RES_3_H,
            0x9D => PrefixOpCode::RES_3_L,
            0x9E => PrefixOpCode::RES_3_HLcontents,
            0x9F => PrefixOpCode::RES_3_A,
            // Ax
            0xA0 => PrefixOpCode::RES_4_B,
            0xA1 => PrefixOpCode::RES_4_C,
            0xA2 => PrefixOpCode::RES_4_D,
            0xA3 => PrefixOpCode::RES_4_E,
            0xA4 => PrefixOpCode::RES_4_H,
            0xA5 => PrefixOpCode::RES_4_L,
            0xA6 => PrefixOpCode::RES_4_HLcontents,
            0xA7 => PrefixOpCode::RES_4_A,
            0xA8 => PrefixOpCode::RES_5_B,
            0xA9 => PrefixOpCode::RES_5_C,
            0xAA => PrefixOpCode::RES_5_D,
            0xAB => PrefixOpCode::RES_5_E,
            0xAC => PrefixOpCode::RES_5_H,
            0xAD => PrefixOpCode::RES_5_L,
            0xAE => PrefixOpCode::RES_5_HLcontents,
            0xAF => PrefixOpCode::RES_5_A,
            // Bx
            0xB0 => PrefixOpCode::RES_6_B,
            0xB1 => PrefixOpCode::RES_6_C,
            0xB2 => PrefixOpCode::RES_6_D,
            0xB3 => PrefixOpCode::RES_6_E,
            0xB4 => PrefixOpCode::RES_6_H,
            0xB5 => PrefixOpCode::RES_6_L,
            0xB6 => PrefixOpCode::RES_6_HLcontents,
            0xB7 => PrefixOpCode::RES_6_A,
            0xB8 => PrefixOpCode::RES_7_B,
            0xB9 => PrefixOpCode::RES_7_C,
            0xBA => PrefixOpCode::RES_7_D,
            0xBB => PrefixOpCode::RES_7_E,
            0xBC => PrefixOpCode::RES_7_H,
            0xBD => PrefixOpCode::RES_7_L,
            0xBE => PrefixOpCode::RES_7_HLcontents,
            0xBF => PrefixOpCode::RES_7_A,
            // Cx
            0xC0 => PrefixOpCode::SET_0_B,
            0xC1 => PrefixOpCode::SET_0_C,
            0xC2 => PrefixOpCode::SET_0_D,
            0xC3 => PrefixOpCode::SET_0_E,
            0xC4 => PrefixOpCode::SET_0_H,
            0xC5 => PrefixOpCode::SET_0_L,
            0xC6 => PrefixOpCode::SET_0_HLcontents,
            0xC7 => PrefixOpCode::SET_0_A,
            0xC8 => PrefixOpCode::SET_1_B,
            0xC9 => PrefixOpCode::SET_1_C,
            0xCA => PrefixOpCode::SET_1_D,
            0xCB => PrefixOpCode::SET_1_E,
            0xCC => PrefixOpCode::SET_1_H,
            0xCD => PrefixOpCode::SET_1_L,
            0xCE => PrefixOpCode::SET_1_HLcontents,
            0xCF => PrefixOpCode::SET_1_A,
            // Dx
            0xD0 => PrefixOpCode::SET_2_B,
            0xD1 => PrefixOpCode::SET_2_C,
            0xD2 => PrefixOpCode::SET_2_D,
            0xD3 => PrefixOpCode::SET_2_E,
            0xD4 => PrefixOpCode::SET_2_H,
            0xD5 => PrefixOpCode::SET_2_L,
            0xD6 => PrefixOpCode::SET_2_HLcontents,
            0xD7 => PrefixOpCode::SET_2_A,
            0xD8 => PrefixOpCode::SET_3_B,
            0xD9 => PrefixOpCode::SET_3_C,
            0xDA => PrefixOpCode::SET_3_D,
            0xDB => PrefixOpCode::SET_3_E,
            0xDC => PrefixOpCode::SET_3_H,
            0xDD => PrefixOpCode::SET_3_L,
            0xDE => PrefixOpCode::SET_3_HLcontents,
            0xDF => PrefixOpCode::SET_3_A,
            // Ex
            0xE0 => PrefixOpCode::SET_4_B,
            0xE1 => PrefixOpCode::SET_4_C,
            0xE2 => PrefixOpCode::SET_4_D,
            0xE3 => PrefixOpCode::SET_4_E,
            0xE4 => PrefixOpCode::SET_4_H,
            0xE5 => PrefixOpCode::SET_4_L,
            0xE6 => PrefixOpCode::SET_4_HLcontents,
            0xE7 => PrefixOpCode::SET_4_A,
            0xE8 => PrefixOpCode::SET_5_B,
            0xE9 => PrefixOpCode::SET_5_C,
            0xEA => PrefixOpCode::SET_5_D,
            0xEB => PrefixOpCode::SET_5_E,
            0xEC => PrefixOpCode::SET_5_H,
            0xED => PrefixOpCode::SET_5_L,
            0xEE => PrefixOpCode::SET_5_HLcontents,
            0xEF => PrefixOpCode::SET_5_A,
            // Fx
            0xF0 => PrefixOpCode::SET_6_B,
            0xF1 => PrefixOpCode::SET_6_C,
            0xF2 => PrefixOpCode::SET_6_D,
            0xF3 => PrefixOpCode::SET_6_E,
            0xF4 => PrefixOpCode::SET_6_H,
            0xF5 => PrefixOpCode::SET_6_L,
            0xF6 => PrefixOpCode::SET_6_HLcontents,
            0xF7 => PrefixOpCode::SET_6_A,
            0xF8 => PrefixOpCode::SET_7_B,
            0xF9 => PrefixOpCode::SET_7_C,
            0xFA => PrefixOpCode::SET_7_D,
            0xFB => PrefixOpCode::SET_7_E,
            0xFC => PrefixOpCode::SET_7_H,
            0xFD => PrefixOpCode::SET_7_L,
            0xFE => PrefixOpCode::SET_7_HLcontents,
            0xFF => PrefixOpCode::SET_7_A,
        }
    }
}

pub enum PrefixOpCode {
    // 0x
    RLC_B = 0x00,
    RLC_C = 0x01,
    RLC_D = 0x02,
    RLC_E = 0x03,
    RLC_H = 0x04,
    RLC_L = 0x05,
    RLC_HLcontents = 0x06,
    RLC_A = 0x07,
    RRC_B = 0x08,
    RRC_C = 0x09,
    RRC_D = 0x0A,
    RRC_E = 0x0B,
    RRC_H = 0x0C,
    RRC_L = 0x0D,
    RRC_HLcontents = 0x0E,
    RRC_A = 0x0F,

    // 1x
    RL_B = 0x10,
    RL_C = 0x11,
    RL_D = 0x12,
    RL_E = 0x13,
    RL_H = 0x14,
    RL_L = 0x15,
    RL_HLcontents = 0x16,
    RL_A = 0x17,
    RR_B = 0x18,
    RR_C = 0x19,
    RR_D = 0x1A,
    RR_E = 0x1B,
    RR_H = 0x1C,
    RR_L = 0x1D,
    RR_HLcontents = 0x1E,
    RR_A = 0x1F,

    // 2x
    SLA_B = 0x20,
    SLA_C = 0x21,
    SLA_D = 0x22,
    SLA_E = 0x23,
    SLA_H = 0x24,
    SLA_L = 0x25,
    SLA_HLcontents = 0x26,
    SLA_A = 0x27,
    SRA_B = 0x28,
    SRA_C = 0x29,
    SRA_D = 0x2A,
    SRA_E = 0x2B,
    SRA_H = 0x2C,
    SRA_L = 0x2D,
    SRA_HLcontents = 0x2E,
    SRA_A = 0x2F,

    // 3x
    SWAP_B = 0x30,
    SWAP_C = 0x31,
    SWAP_D = 0x32,
    SWAP_E = 0x33,
    SWAP_H = 0x34,
    SWAP_L = 0x35,
    SWAP_HLcontents = 0x36,
    SWAP_A = 0x37,
    SRL_B = 0x38,
    SRL_C = 0x39,
    SRL_D = 0x3A,
    SRL_E = 0x3B,
    SRL_H = 0x3C,
    SRL_L = 0x3D,
    SRL_HLcontents = 0x3E,
    SRL_A = 0x3F,

    // 4x
    BIT_0_B = 0x40,
    BIT_0_C = 0x41,
    BIT_0_D = 0x42,
    BIT_0_E = 0x43,
    BIT_0_H = 0x44,
    BIT_0_L = 0x45,
    BIT_0_HLcontents = 0x46,
    BIT_0_A = 0x47,
    BIT_1_B = 0x48,
    BIT_1_C = 0x49,
    BIT_1_D = 0x4A,
    BIT_1_E = 0x4B,
    BIT_1_H = 0x4C,
    BIT_1_L = 0x4D,
    BIT_1_HLcontents = 0x4E,
    BIT_1_A = 0x4F,

    // 5x
    BIT_2_B = 0x50,
    BIT_2_C = 0x51,
    BIT_2_D = 0x52,
    BIT_2_E = 0x53,
    BIT_2_H = 0x54,
    BIT_2_L = 0x55,
    BIT_2_HLcontents = 0x56,
    BIT_2_A = 0x57,
    BIT_3_B = 0x58,
    BIT_3_C = 0x59,
    BIT_3_D = 0x5A,
    BIT_3_E = 0x5B,
    BIT_3_H = 0x5C,
    BIT_3_L = 0x5D,
    BIT_3_HLcontents = 0x5E,
    BIT_3_A = 0x5F,

    // 6x
    BIT_4_B = 0x60,
    BIT_4_C = 0x61,
    BIT_4_D = 0x62,
    BIT_4_E = 0x63,
    BIT_4_H = 0x64,
    BIT_4_L = 0x65,
    BIT_4_HLcontents = 0x66,
    BIT_4_A = 0x67,
    BIT_5_B = 0x68,
    BIT_5_C = 0x69,
    BIT_5_D = 0x6A,
    BIT_5_E = 0x6B,
    BIT_5_H = 0x6C,
    BIT_5_L = 0x6D,
    BIT_5_HLcontents = 0x6E,
    BIT_5_A = 0x6F,

    // 7x
    BIT_6_B = 0x70,
    BIT_6_C = 0x71,
    BIT_6_D = 0x72,
    BIT_6_E = 0x73,
    BIT_6_H = 0x74,
    BIT_6_L = 0x75,
    BIT_6_HLcontents = 0x76,
    BIT_6_A = 0x77,
    BIT_7_B = 0x78,
    BIT_7_C = 0x79,
    BIT_7_D = 0x7A,
    BIT_7_E = 0x7B,
    BIT_7_H = 0x7C,
    BIT_7_L = 0x7D,
    BIT_7_HLcontents = 0x7E,
    BIT_7_A = 0x7F,

    // 8x
    RES_0_B = 0x80,
    RES_0_C = 0x81,
    RES_0_D = 0x82,
    RES_0_E = 0x83,
    RES_0_H = 0x84,
    RES_0_L = 0x85,
    RES_0_HLcontents = 0x86,
    RES_0_A = 0x87,
    RES_1_B = 0x88,
    RES_1_C = 0x89,
    RES_1_D = 0x8A,
    RES_1_E = 0x8B,
    RES_1_H = 0x8C,
    RES_1_L = 0x8D,
    RES_1_HLcontents = 0x8E,
    RES_1_A = 0x8F,

    // 9x
    RES_2_B = 0x90,
    RES_2_C = 0x91,
    RES_2_D = 0x92,
    RES_2_E = 0x93,
    RES_2_H = 0x94,
    RES_2_L = 0x95,
    RES_2_HLcontents = 0x96,
    RES_2_A = 0x97,
    RES_3_B = 0x98,
    RES_3_C = 0x99,
    RES_3_D = 0x9A,
    RES_3_E = 0x9B,
    RES_3_H = 0x9C,
    RES_3_L = 0x9D,
    RES_3_HLcontents = 0x9E,
    RES_3_A = 0x9F,

    // Ax
    RES_4_B = 0xA0,
    RES_4_C = 0xA1,
    RES_4_D = 0xA2,
    RES_4_E = 0xA3,
    RES_4_H = 0xA4,
    RES_4_L = 0xA5,
    RES_4_HLcontents = 0xA6,
    RES_4_A = 0xA7,
    RES_5_B = 0xA8,
    RES_5_C = 0xA9,
    RES_5_D = 0xAA,
    RES_5_E = 0xAB,
    RES_5_H = 0xAC,
    RES_5_L = 0xAD,
    RES_5_HLcontents = 0xAE,
    RES_5_A = 0xAF,

    // Bx
    RES_6_B = 0xB0,
    RES_6_C = 0xB1,
    RES_6_D = 0xB2,
    RES_6_E = 0xB3,
    RES_6_H = 0xB4,
    RES_6_L = 0xB5,
    RES_6_HLcontents = 0xB6,
    RES_6_A = 0xB7,
    RES_7_B = 0xB8,
    RES_7_C = 0xB9,
    RES_7_D = 0xBA,
    RES_7_E = 0xBB,
    RES_7_H = 0xBC,
    RES_7_L = 0xBD,
    RES_7_HLcontents = 0xBE,
    RES_7_A = 0xBF,

    // Cx
    SET_0_B = 0xC0,
    SET_0_C = 0xC1,
    SET_0_D = 0xC2,
    SET_0_E = 0xC3,
    SET_0_H = 0xC4,
    SET_0_L = 0xC5,
    SET_0_HLcontents = 0xC6,
    SET_0_A = 0xC7,
    SET_1_B = 0xC8,
    SET_1_C = 0xC9,
    SET_1_D = 0xCA,
    SET_1_E = 0xCB,
    SET_1_H = 0xCC,
    SET_1_L = 0xCD,
    SET_1_HLcontents = 0xCE,
    SET_1_A = 0xCF,

    // Dx
    SET_2_B = 0xD0,
    SET_2_C = 0xD1,
    SET_2_D = 0xD2,
    SET_2_E = 0xD3,
    SET_2_H = 0xD4,
    SET_2_L = 0xD5,
    SET_2_HLcontents = 0xD6,
    SET_2_A = 0xD7,
    SET_3_B = 0xD8,
    SET_3_C = 0xD9,
    SET_3_D = 0xDA,
    SET_3_E = 0xDB,
    SET_3_H = 0xDC,
    SET_3_L = 0xDD,
    SET_3_HLcontents = 0xDE,
    SET_3_A = 0xDF,

    // Ex
    SET_4_B = 0xE0,
    SET_4_C = 0xE1,
    SET_4_D = 0xE2,
    SET_4_E = 0xE3,
    SET_4_H = 0xE4,
    SET_4_L = 0xE5,
    SET_4_HLcontents = 0xE6,
    SET_4_A = 0xE7,
    SET_5_B = 0xE8,
    SET_5_C = 0xE9,
    SET_5_D = 0xEA,
    SET_5_E = 0xEB,
    SET_5_H = 0xEC,
    SET_5_L = 0xED,
    SET_5_HLcontents = 0xEE,
    SET_5_A = 0xEF,

    // Fx
    SET_6_B = 0xF0,
    SET_6_C = 0xF1,
    SET_6_D = 0xF2,
    SET_6_E = 0xF3,
    SET_6_H = 0xF4,
    SET_6_L = 0xF5,
    SET_6_HLcontents = 0xF6,
    SET_6_A = 0xF7,
    SET_7_B = 0xF8,
    SET_7_C = 0xF9,
    SET_7_D = 0xFA,
    SET_7_E = 0xFB,
    SET_7_H = 0xFC,
    SET_7_L = 0xFD,
    SET_7_HLcontents = 0xFE,
    SET_7_A = 0xFF,
}
